language: python
cache:
  directories:
    - "/home/travis/virtualenv/python2.7.9/"
python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install: make setup
script: make test
